### ISSUE TITLE
v2-1 failed to build on mac os

### ISSUE THREAD

**Issue by shi-yan** [OGRECave/ogre-next#1]
#### System Information
- Ogre Version: :grey_question: v2-1
- Operating System / Platform: :grey_question: mac os mojave 
- RenderSystem: :grey_question: opengl

#### Detailled description
code failed to build on mac os with xcode/clang 10

#### Ogre.log

the following code fails to build on mac os with clang 10

```
namespace std
{
    #if __cplusplus < 201103L && OGRE_PLATFORM != OGRE_PLATFORM_EMSCRIPTEN
    namespace tr1
    {__cplusplus
    #endif
        template < typename T >
        struct hash< Ogre::SharedPtr< T > > : hash< T* >
        {
            typedef hash< T* > MyBase;
            typedef Ogre::SharedPtr< T > argument_type;
            typedef size_t result_type;

            result_type operator()( const argument_type& k ) const
            {
                return MyBase::operator()( k.get() );
            }
        };
    #if __cplusplus < 201103L && OGRE_PLATFORM != OGRE_PLATFORM_EMSCRIPTEN
    }
    #endif
}
```

the compiler complains about the namespace.
the root cause is that __cplusplus is incorrectly set to 199711L 

looking at the cmake file:

```
  set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_STANDARD "c++11")
```

this code doesn't work at all, because if check make command with make VERBOSE=1, there is no -std=c++11 flag set.

I have to use

```
cmake -DCMAKE_CXX_FLAGS="-std=c++11 -stdlib=libc++" 
```

this issue is the same as https://github.com/openscenegraph/OpenSceneGraph/issues/637

**Comment by darksylinc** [comment]
macOS build process has changed significantly since this ticket was created, and there are new instructions on how to get it working with make generator.
