### ISSUE TITLE
Compilation error on Mac and Windows

### ISSUE THREAD

**Issue by Ravbug** [OGRECave/ogre-next#125]
#### System Information
- Ogre Version: 2.2.3
- Operating System / Platform: macOS 10.15.5, Windows 10 1909
- RenderSystem: :grey_question: N/A
- GPU: N/A

#### Detailled description
When compiling on Mac and Windows, the build system cannot find a header in FreeImage:
```cpp
ogre-next/OgreMain/src/OgreFreeImageCodec2.cpp:49:10: fatal error: 'FreeImage.h' file not found
#include <FreeImage.h>
         ^~~~~~~~~~~~~
```

Ogre is configured from a CMakeLists.txt using `add_subdirectory` like this:
```cmake
# .....

# build OGRE
if(WIN32)
	list(APPEND EXTRA_LIBS vcruntime user32 gdi32 winmm imm32 ole32 oleaut32 version uuid advapi32 setupapi shell32)
	
endif()
cmake_policy(SET CMP0021 OLD)                                    # Address CMake relative paths issue
set(OGRE_ROOT "${CMAKE_SOURCE_DIR}/orge-next/")
set(FreeImage_INCLUDE_DIR "${OGRE_ROOT}/Dependencies/src/FreeImage/Source/")
set(OGRE_DEPENDENCIES_DIR "${OGRE_ROOT}/Dependencies")
set(ZLIB_INCLUDE_DIR "${OGRE_ROOT}/Dependencies/src/zlib")
set(OGRE_BUILD_LIBS_AS_FRAMEWORKS OFF)
ProcessorCount(OGRE_CONFIG_THREADS)
if(APPLE)
	set(OGRE_BUILD_RENDERSYSTEM_GL3PLUS OFF)	# disable OpenGL on Mac
endif()
set(CMAKE_CXX_STANDARD 11)						# OGRE requires C++11
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_subdirectory("ogre-next")

# .....
```
I used mercurial to clone Ogre v2 and its dependencies by following the guides on the documentation linked here: [Windows guide](https://ogrecave.github.io/ogre-next/api/2.2/_setting_up_ogre_windows.html) / [Mac guide](https://ogrecave.github.io/ogre-next/api/2.2/_setting_up_ogre_mac_o_s.html)

#### Ogre.log
N/A

#### Callstack
N/A

**Comment by mimon** [comment]
Does CMAKE find the freeimage files during the configure step?
Maybe you could try to print the full compilation command that Cmake generates to see what flags it passes to the compiler?

**Comment by darksylinc** [comment]
Mercurial??? When did the docs revert back? **Sigh**

**For some reason the docs are not up to date.** Perhaps it's time for me to try to merge those PR to automatically generate the docs.

Anyway, my biggest recommendation until the docs are updated is that you try the [quick build scripts](https://www.ogre3d.org/download/sdk/sdk-ogre-next) since they work out of the box for Windows (there is no script for macOS)

The error in particular you're having is because FreeImage from the [ogre-next-deps](https://github.com/OGRECave/ogre-next-deps) was not setup correctly.

For it to work out of the box, ogre-next_Repo/Dependencies should point to ogre-next-deps_Repo/build/ogredeps

Try to setup Windows first since it's a much easier target to setup than Mac, once you have that one working you can try getting the macOS version up and running

**Comment by Ravbug** [comment]
I have updated the dependencies from GitHub, and the FreeImage header problem is resolved. However, on Mac it fails to link with this message:
```sh
ld: library not found for -latomic
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Full command invoked by Xcode:
```sh
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target x86_64-apple-macos10.15 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -L/Users/main/Documents/Engine/build/ogre-next/lib/macosx/debug -F/Users/main/Documents/Engine/build/ogre-next/lib/macosx/debug -filelist /Users/main/Documents/Engine/build/ogre-next/OgreMain/Engine.build/debug/OgreMain.build/Objects-normal/x86_64/Ogre.LinkFileList -install_name @executable_path/../Frameworks/Ogre.framework/Versions/2.3.0/Ogre -Xlinker -object_path_lto -Xlinker /Users/main/Documents/Engine/build/ogre-next/OgreMain/Engine.build/debug/OgreMain.build/Objects-normal/x86_64/Ogre_lto.o -Xlinker -no_deduplicate -fobjc-link-runtime -framework IOKit -framework Cocoa -framework Carbon -framework OpenGL -framework CoreVideo -latomic -compatibility_version 2.3.0 -current_version 2.3.0 -Xlinker -dependency_info -Xlinker /Users/main/Documents/Engine/build/ogre-next/OgreMain/Engine.build/debug/OgreMain.build/Objects-normal/x86_64/Ogre_dependency_info.dat -o /Users/main/Documents/Engine/build/ogre-next/lib/macosx/debug/Ogre.framework/Versions/2.3.0/Ogre
```

Ogre is configured like this in my CMakeLists.txt, using the quick build script as a reference:
```cmake
#cmake_policy(SET CMP0021 OLD)
set(OGRE_ROOT "${CMAKE_SOURCE_DIR}/ogre-next/")
set(OGRE_USE_BOOST OFF)
set(OGRE_CONFIG_THREAD_PROVIDER OFF)
set(OGRE_BUILD_COMPONENT_SCENE_FORMAT ON)
set(OGRE_BUILD_SAMPLES2 ON)
set(OGRE_BUILD_TESTS ON)
set(OGRE_DEPENDENCIES_DIR "${OGRE_ROOT}/Dependencies")
set(OGRE_BUILD_LIBS_AS_FRAMEWORKS OFF)
ProcessorCount(OGRE_CONFIG_THREADS)
if(APPLE)
	set(OGRE_BUILD_RENDERSYSTEM_GL3PLUS OFF)	# disable OpenGL on Mac
endif()
add_subdirectory("ogre-next")
```

**Comment by mimon** [comment]
Someone else had a similiar problem: checkout https://github.com/OGRECave/ogre-next/issues/94#issuecomment-657900710
