### ISSUE TITLE
[OGRE-2.1] Build fails on Linux "fatal error: sys/sysctl.h: No such file or directory"

### ISSUE THREAD

**Issue by Yamakuzure** [OGRECave/ogre-next#132]
The full error is:

````
OgreMain/src/OgrePlatformInformation.cpp:46:18: fatal error: sys/sysctl.h: No such file or directory
   46 |         #include <sys/sysctl.h>
      |                  ^~~~~~~~~~~~~~
compilation terminated.
````

And sure enough, there is no /usr/include/sys/sysctl.h, but /usr/include/linux/sysctl.h - which is something completely different I remember?
Correct me if I am wrong, but isn't <sys/sysctl.h> Apple specific stuff?

However, the following patch fixed the compilation issue for me:
````
--- a/OgreMain/src/OgrePlatformInformation.cpp	2020-08-17 15:31:37.604611731 +0200
+++ /b/OgreMain/src/OgrePlatformInformation.cpp	2020-08-17 15:33:11.268613001 +0200
@@ -42,7 +42,7 @@
 #if OGRE_PLATFORM != OGRE_PLATFORM_WIN32
     #if OGRE_PLATFORM == OGRE_PLATFORM_ANDROID
         #include <linux/sysctl.h>
-    #else
+    #elif OGRE_PLATFORM == OGRE_PLATFORM_APPLE || OGRE_PLATFORM == OGRE_PLATFORM_APPLE_IOS
         #include <sys/sysctl.h>
     #endif
 #endif
````

**Comment by Yamakuzure** [comment]
I have tested some Samples, and everything seems to work fine.

Gentoo Linux
Kernel 5.7.15-gentoo
Compiler: gcc-9.3.0
libc: glibc-2.32

**Comment by darksylinc** [comment]
It looks like indeed may only be needed in iOS platforms only

**Comment by nargil** [comment]
it was removed in glibc 2.32: https://sourceware.org/pipermail/libc-announce/2020/000029.html
we still have <linux/sysctl.h> if needed.

**Comment by Yamakuzure** [comment]
> it was removed in glibc 2.32: https://sourceware.org/pipermail/libc-announce/2020/000029.html
> I blindly fixed my build with <linux/sysctl.h>. Not sure if it's a replacement or just the include is not required.

As far as I could see, it isn't required.
