### ISSUE TITLE
How to retrieve an ogre::Item and retrieve his materialName

### ISSUE THREAD

**Issue by tesseract-solutions** [OGRECave/ogre-next#140]
Hello everyone,

I want to retrieve an ogre::Item from my scene manager. And  i need to retrieve his material name. 

Have you any ideas ? 

Thank you

**Comment by JackHolmes** [comment]
I've only start looking at OGRE today, but this is from what I can gather reading the source:

_Retrieving an Item_
When you added an Item to the scene (via sceneNode->attachObject) you can also get the Id of the node with sceneNode->getId. You can pass this scene node Id into sceneManager->getSceneNode to retrieve the node. Alternatively, you can call sceneManager->findSceneNodes which will return a list of nodes that match the provided string name.

_Retrieving a material name_
An item can consist of multiple SubItem's each containing a reference to a SubMesh. So getting the material name of the SubMesh for the first SubItem would look something like item->getSubItem( 0 )->getSubMesh()->getMaterialName()
