### ISSUE TITLE
Use different texture or color on one part

### ISSUE THREAD

**Issue by florian02100** [OGRECave/ogre-next#178]
Hi everyone,

I try to apply two texture or two color on the same part. 

I can split my part in area to apply a different texture or color ? 

Have you any ideas to realize this operation ? 

Thank you !

**Comment by darksylinc** [comment]
You'll probably get more [help in the forums](https://forums.ogre3d.org/viewforum.php?f=2) as more people look into it (don't forget to clarify you're using Ogre 2.x).

It sounds like what you want to do requires two submeshes. However the way you phrased it is very vague.

**Comment by florian02100** [comment]
Hi,

Thank you !

I move my message to Ogre forum. 

Thank you !
