### ISSUE TITLE
Release build fails missing PlatformInformation header

### ISSUE THREAD

**Issue by dermont123** [OGRECave/ogre-next#180]
The release build for master branch fails due to missing OgrePlatformInformation.h in GraphicsSystem.cpp. I guess related to this update:
https://github.com/OGRECave/ogre-next/commit/1d0ca7fd1ef48e7b8c33282565063df72806d1cc  

`/media/sdb5/Libraries/OGRE/src/master/Samples/2.0/Common/src/GraphicsSystem.cpp:838:62: error: ‘Ogre::PlatformInformation’ has not been declared
  838 |        const size_t numThreads = std::max<size_t>( 1, Ogre::PlatformInformation::getNumLogicalCores() );`

**Comment by darksylinc** [comment]
Closed by https://github.com/OGRECave/ogre-next/pull/179
