### ISSUE TITLE
OgreMemorySTLAllocator.h: "std::allocator<void>::const_pointer" removed in C++20

### ISSUE THREAD

**Issue by knox31085** [OGRECave/ogre-next#203]
#### Detailled description
const_pointer from std::allocator was removed in C++20. This is still used in OgreMemorySTLAllocator.h line 130.

**Comment by darksylinc** [comment]
The line you're referring to is guarded by an ifdef:

```
#if __cplusplus > 201703L
        inline pointer allocate( size_type count )
        {
#else
        inline pointer allocate( size_type count,
            typename std::allocator<void>::const_pointer ptr = 0 )
        {
                        (void)ptr;
#endif
```

Is it not working?

**Comment by knox31085** [comment]
OK. I've overseen this guard since it is not working per default in Visual Studio. I have to manually add the build command line switch "/Zc:__cplusplus" to enable this macro (Or set it to the correct value). If this is missing the macro is always 199711 which is C++98 or C++03. (See: https://docs.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-160).
This is also independent of the selected version of the standart which should be used (Selectable via /std). This means that there can get a situation where you want to use C++17/20 (via /std:c++17) and the __cpluscplus-Macro which states that you use C++98/03...... 
I really don't know what MS has thought with the seperation of the switches...

Ogre-Code is correct at this point.

Thanks
