### ISSUE TITLE
cmake: OGRE_GLSUPPORT_NUM_INTERFACES has no default value 

### ISSUE THREAD

**Issue by busovikov** [OGRECave/ogre-next#206]
#### System Information
- Ogre Version: 2.2.5 tag / master also
- Operating System / Platform: Windows
- Cmake Version 3.3.2

#### Detailled description
Configuring cmake cause the error as follow:

CMake Error at CMakeLists.txt:417 (math):
  math cannot parse the expression: " + 1": syntax error, unexpected
  exp_PLUS, expecting exp_OPENPARENT or exp_NUMBER (2)

The reason is that OGRE_GLSUPPORT_NUM_INTERFACES is not set to default and therefore 
math( EXPR OGRE_GLSUPPORT_NUM_INTERFACES "${OGRE_GLSUPPORT_NUM_INTERFACES} + 1" )
makes an expression as "+ 1"

It might be better to set default

Regards

**Comment by darksylinc** [comment]
As a temporary workaround until this is resolved, I suggest you try a newer CMake version, as this error doesn't happen in newer CMake releases.

**Comment by busovikov** [comment]
Thanks!
