### ISSUE TITLE
Pixel shader build error using Terra system without a compositor shadow node

### ISSUE THREAD

**Issue by TaaTT4** [OGRECave/ogre-next#239]
Commit https://github.com/OGRECave/ogre-next/commit/b18f7a37da2ad24765fdcc12f52a94e08ac35e8d introduced a pixel shader build error:
```
09:30:29: OGRE EXCEPTION(-2147467259:RenderingAPIException): Cannot compile D3D11 high-level shader 100000002PixelShader_ps Errors:
S:\App\Playground\build\bin\Debug\Playground\local\Debug\HLMS\HLSL\100000002PixelShader_ps.hlsl(909,4-10): error X3004: undeclared identifier 'fShadow'
 in D3D11HLSLProgram::compileMicrocode at D:\Development\SDK\OGRE\OGRE\RenderSystems\Direct3D11\src\OgreD3D11HLSLProgram.cpp (line 539)
09:30:29: High-level program 100000002PixelShader_ps encountered an error during loading and is thus not supported.
```

Step to reproduce:
- Disable `Tutorial_TerrainShadowNode` from `Tutorial_TerrainRenderingNode` in `Sample_Tutorial_Terrain`

**Comment by darksylinc** [comment]
Grrr I was sure I tested this. I wonder if it's a D3D11 specific issue.

Thanks

**Comment by TaaTT4** [comment]
You're out of luck, it's cross-render system.
I guess it's related to the fact that Terra system [forces `HlmsBaseProp::LightsDirectional`](https://github.com/OGRECave/ogre-next/blob/master/Samples/2.0/Tutorials/Tutorial_Terrain/src/Terra/Hlms/PbsListener/OgreHlmsPbsTerraShadows.cpp#L109) just taking in account the case when directional light shadow casting is turned off by user (and not also the case when [shadow node is not present](https://github.com/OGRECave/ogre-next/blob/master/OgreMain/src/OgreHlms.cpp#L2622)).
