### ISSUE TITLE
Source clean up for 2.3 release?

### ISSUE THREAD

**Issue by oldmanauz** [OGRECave/ogre-next#245]
@darksylinc, In preperation for a 2.3 release soon(I'm guessing ??) I was looking around the code and to me it looked like a lot of legecy code could be cleaned up. I can do a PR for it, I just wanted to check if it was a good idea or not. Potential clean ups:
1. Components cleanup:
  - `Paging` component source removed - Ogre code that hasn't been ported to Ogre Next yet?
  - `RTShaderSystem` component source removed - legecy code from Ogre that isn't used anymore?
  - `Terrain` component source removed - Ogre code that hasn't been ported to Ogre Next yet?
  - `Volume` component source removed - Ogre code that hasn't been ported to Ogre Next yet?
2. Plugin cleanup:
  - `BSP plugin` source removed - Ogre code that hasn't been ported to Ogre Next yet?
  - `Octree Scene Manager plugin` source removed - Ogre code that hasn't been ported to Ogre Next yet?
  - `Octree Zone plugin` source removed - Ogre code that hasn't been ported to Ogre Next yet?
  - `PCZ Scene Manager plugin` source removed - Ogre code that hasn't been ported to Ogre Next yet?
3. Rendersystem cleanup:
  - `DirectX9 Render System` source removed - legecy code from Ogre that isn't used anymore?
  - `GLES2 Render System` source removed - legecy code from Ogre that isn't used anymore?
4. NaCl platform removal - legecy code from Ogre that isn't used anymore?
5. Clean up `Media` folder and remove unused stuff from Ogre samples.
6. `CMAKE` cleanup:
  - Remove legecy componetns, plugins and rendersystems from the configuration
  - Remove the threading config options: `OGRE_CONFIG_THREADS` & `OGRE_CONFIG_THREADS_PROVIDER`
  - Remove boost stuff from CMAKE - assuming this isn't used anywhere any more?
7. Any interest in a refresh for the docs? Options I breifly looked at.
  - New docs systems. This is potentially a lot of mucking around so not sure it is a great idea.
    - Docsforge [flecs example](https://flecs.docsforge.com/) is nicer to search
    - Sphinx [bgfx example](https://bkaradzic.github.io/bgfx/index.html)
  - New theme for doxygen like [doxygen awesome](https://jothepro.github.io/doxygen-awesome-css/)  (Night mode - wow!)
  - New style as per #84 

Thoughts?

**Comment by darksylinc** [comment]
Ticket https://github.com/OGRECave/ogre-next/issues/235 is for 2.4 and will focus on a long needed cleanup

I don't want to rock the boat so close to 2.3's release (I've hady hands full past three weeks, which is why we haven't released yet)

Some of the stuff you're mentioning should be added to that ticket

**Comment by oldmanauz** [comment]
I'll merge these ideas with that and close.

**Comment by darksylinc** [comment]
Another reason is that I want to do the name change before it has lots of merge conflicts due to deleted/moved files
