### ISSUE TITLE
setting OGRE_DEBUG_MODE without warning based on DEBUG is tricky 

### ISSUE THREAD

**Issue by rpaciorek** [OGRECave/ogre-next#263]
#### System Information
- Ogre Version: 2.4

#### Detailed description

Ogre in `OgrePlatform.h` try set `OGRE_DEBUG_MODE` based on `NDEBUG`, `_DEBUG` and `DEBUG`.

This can be very tricky (especially when some header file included before Ogre set DEBUG without warning - e.g. [CEGUI#1248](https://github.com/cegui/cegui/issues/1248) because OGRE_DEBUG_MODE affects object size and data offset (e.g. IdString).

#### Suggested fix

Recommended define `OGRE_DEBUG_MODE` macro and always generate warning when `OGRE_DEBUG_MODE` is not define and Ogre guess it value based on other macros.

**Comment by darksylinc** [comment]
Hi!

This task is being tracked by #235 (Add cmake option to embed debug level into OgreBuildSettings &  Pass cookie to Ogre Root initialization to catch obvious ABI errors)

Currently the only workaround I can offer is to manually define OGRE_DEBUG_MODE when invoking g++/clang/cl.exe

> Recommended define OGRE_DEBUG_MODE macro and always generate warning when OGRE_DEBUG_MODE is not define and Ogre guess it value based on other macros.

It's a bit more tricky. On platforms that can switch between Debug & Release projects (e.g. Visual Studio & XCode) auto-detect via NDEBUG/DEBUG/_DEBUG macros.

But in certain cases (such as GNU Make, Ninja, and other cases where only one version of Ogre has been prebuilt) we want OGRE_DEBUG_MODE to be baked into OgreBuildSettings.h

Thus the solution we're thinking of is to add a CMake parameter to bake OGRE_DEBUG_MODE into OgreBuildSettings.h; which is on by default on Ninja/GNU Make generators and disabled for the rest.

**Comment by rpaciorek** [comment]
> But in certain cases (such as GNU Make, Ninja, and other cases where only one version of Ogre has been prebuilt) we want OGRE_DEBUG_MODE to be baked into OgreBuildSettings.h
>
> Thus the solution we're thinking of is to add a CMake parameter to bake OGRE_DEBUG_MODE into OgreBuildSettings.h; which is on by default on Ninja/GNU Make generators and disabled for the rest.

sounds good :)

**Comment by darksylinc** [comment]
I pushed a new CMake option [OGRE_EMBED_DEBUG_MODE](https://github.com/OGRECave/ogre-next/commit/100db3dccc393dba48fae08dc2ea191015cf4195) to address this issue.

The default option 'auto' should be enough for everyone, but it also supports "always" and "never".
