### ISSUE TITLE
The decode function in OgreSTBICodec.cpp has bug when decode 24 byte Images

### ISSUE THREAD

**Issue by 36yang** [OGRECave/ogre-next#268]
#### System Information
- Ogre Version: :grey_question:  ogre-next
- Operating System / Platform: :grey_question:win10 
- RenderSystem: :grey_question:dx11
- GPU: :grey_question:gtx3060

#### Detailled description

When I use jpg or 24 byte png Image Files as the pbr diffuse_map. It not show  any thing at all. 
Then I find the problem is the decode function in OgreSTBICodec.cpp has bug。 When the channel
is 3,  Inside the for loop on line 169. The condition should be < instead of << , but there are still other problems that cause crashes, which I haven't found yet。

**Comment by darksylinc** [comment]
You fixed this via #317

Thanks.
