### ISSUE TITLE
Fix Github Pages entry point

### ISSUE THREAD

**Issue by darksylinc** [OGRECave/ogre-next#28]
We carried over from 1.x's Github Pages

Our current main page:
https://ogrecave.github.io/ogre-next/

Talks about 1.x and points to manuals for these versions.

**Comment by Ybalrid** [comment]
If I have nothing better to do this week end, I'll PR against your gh-pages banches to fix manual links and make it refer to ogre-next instead of ogre. 

Also, I'll check if the 2.x doxygen are up-to-date...

**Comment by darksylinc** [comment]
The doxygen _should_ be up to date since I built it recently.

But really what's completely wrong is the entry point https://ogrecave.github.io/ogre-next/

Not just the links, but also almost all of it is relevant to 1.x, not 2.x

A few things can still be kept (the "Literature" section is still slightly relevant to 2.x, I believe there is a port of Particle Universe to 2.1, etc)

**Comment by Ybalrid** [comment]
Noted.

Also, will move to the newer, moderner logo on the page header :wink:
