### ISSUE TITLE
Linux soname mismatch in DynLib

### ISSUE THREAD

**Issue by dermont123** [OGRECave/ogre-next#290]
OgreDynLib.cpp
            name += ".so.";
            name += StringConverter::toString( OGRE_VERSION_MAJOR ) + ".";
            name += StringConverter::toString( OGRE_VERSION_MINOR ); 
            //+ ".";
            //name += StringConverter::toString( OGRE_VERSION_PATCH );

https://github.com/OGRECave/ogre-next/commit/14a560c29b26d412582daab4f1b1f2238a9cf7d8

**Comment by darksylinc** [comment]
Thanks.

Yesterday I was on so many things I didn't realize I didn't test whether it runs! :cry:
