### ISSUE TITLE
error: use of undeclared identifier 'atmoSettings' on iOS

### ISSUE THREAD

**Issue by Hotshot5000** [OGRECave/ogre-next#300]
#### System Information
- Ogre Version: a2c9b18784ed5f32cab6ff0ad34788a47f2169f7 latest from master branch
- Operating System / Platform: iOS 15.5 Ogre built on macbook pro M1
- RenderSystem: Metal
- GPU: :grey_question:

#### Detailled description
Tried running pbsmaterial sample

**Comment by darksylinc** [comment]
Interesting. I will take a look.

Either the Atmo paths were not correctly included or registered; or PBS is trying to use Atmo when Ogre was not build with it.

Do you know what's the status of `OGRE_BUILD_COMPONENT_ATMOSPHERE` ? 
You can check it in either `CMakeCache.txt` or `OgreBuildSettings.h`

**Comment by Hotshot5000** [comment]
OgreBuildSettings.h

#ifndef __Custom_Config_H_
#define __Custom_Config_H_

// CMake auto-generated configuration options

#define OGRE_STATIC_LIB
#define OGRE_DEBUG_LEVEL_DEBUG 3
#define OGRE_DEBUG_LEVEL_RELEASE 0

#if 0
#    define OGRE_DEBUG_MODE 
#endif

/* #undef OGRE_BUILD_RENDERSYSTEM_D3D11 */
/* #undef OGRE_BUILD_RENDERSYSTEM_GL3PLUS */
/* #undef OGRE_BUILD_RENDERSYSTEM_GLES */
/* #undef OGRE_BUILD_RENDERSYSTEM_GLES2 */
#define OGRE_BUILD_RENDERSYSTEM_METAL
/* #undef OGRE_BUILD_RENDERSYSTEM_VULKAN */
#define OGRE_BUILD_PLUGIN_PFX
#define OGRE_BUILD_COMPONENT_ATMOSPHERE
#define OGRE_BUILD_COMPONENT_HLMS_PBS
#define OGRE_BUILD_COMPONENT_HLMS_UNLIT
/* #undef OGRE_BUILD_COMPONENT_PAGING */
/* #undef OGRE_BUILD_COMPONENT_PLANAR_REFLECTIONS */
/* #undef OGRE_BUILD_COMPONENT_SCENE_FORMAT */
#define OGRE_BUILD_COMPONENT_MESHLODGENERATOR
/* #undef OGRE_BUILD_COMPONENT_TERRAIN */
/* #undef OGRE_BUILD_COMPONENT_VOLUME */
/* #undef OGRE_BUILD_COMPONENT_PROPERTY */
#define OGRE_BUILD_COMPONENT_OVERLAY

#define OGRE_CONFIG_LITTLE_ENDIAN
/* #undef OGRE_CONFIG_BIG_ENDIAN */
/* #undef OGRE_CONFIG_UNIX_NO_X11 */

#define OGRE_DOUBLE_PRECISION 0

#define OGRE_NODE_INHERIT_TRANSFORM 0

#define OGRE_MEMORY_ALLOCATOR 0

#define OGRE_CONTAINERS_USE_CUSTOM_MEMORY_ALLOCATOR 0

#define OGRE_STRING_USE_CUSTOM_MEMORY_ALLOCATOR 0

#define OGRE_MEMORY_TRACKER_DEBUG_MODE 0

#define OGRE_MEMORY_TRACKER_RELEASE_MODE 0

#define OGRE_ASSERT_MODE 0

#define OGRE_THREAD_SUPPORT 0

#define OGRE_THREAD_PROVIDER 0

#define OGRE_NO_MESHLOD 0

#define OGRE_NO_FREEIMAGE 0

#define OGRE_NO_JSON 0

#define OGRE_NO_DDS_CODEC 0

#define OGRE_NO_PVRTC_CODEC 0

#define OGRE_NO_ETC_CODEC 1

#define OGRE_NO_STBI_CODEC 1

#define OGRE_NO_ASTC_CODEC 0

#define OGRE_NO_ZIP_ARCHIVE 0

#define OGRE_NO_VIEWPORT_ORIENTATIONMODE 1

#define OGRE_NO_GLES2_GLSL_OPTIMISER 1

#define OGRE_NO_GLES2_VAO_SUPPORT 1

#define OGRE_NO_GL_STATE_CACHE_SUPPORT 1

#define OGRE_NO_GLES3_SUPPORT 1

#define OGRE_NO_RENDERDOC_INTEGRATION 1

#define OGRE_NO_TBB_SCHEDULER 0

#define OGRE_PROFILING 0

#define OGRE_PROFILING_EXHAUSTIVE 0

#define OGRE_NO_QUAD_BUFFER_STEREO 1

#define OGRE_NO_AMD_AGS 1

#define OGRE_NO_FINE_LIGHT_MASK_GRANULARITY 1

#define OGRE_ENABLE_LIGHT_OBB_RESTRAINT 0

#define OGRE_USE_SIMD 1

#define OGRE_RESTRICT_ALIASING 1

#define OGRE_IDSTRING_ALWAYS_READABLE 0

#endif

**Comment by darksylinc** [comment]
I see!!

Then there's 2 posibilities:

1. The folder `Samples/Media/Hlms/Pbs/Any/Atmosphere` is not being bundled (registered by `HlmsPbs::getDefaultPaths`)
2. `VertexShader_vs.metal`/`PixelShader_ps.metal` is lacking an `@insertpiece( AtmosphereNprSkyDecl )` or is under the wrong properties or it went wrong for whatever reason.

**Comment by Hotshot5000** [comment]
@insertpiece( AtmosphereNprSkyDecl ) doesn't seem to be missing in the .metal files.
Is there a way to force a log/print of the shader after all the macros get expanded directly into the console.
I remember that on desktop I had access to these assembled shaders where the Ogre.log file was created but on iOS I tried downloading the container from the phone but I can't find these files.

**Comment by darksylinc** [comment]
OK I found various problems with it. I'll push the fixes in a second

**Comment by darksylinc** [comment]
Done. Let me know if you have any further problems. It should be fixed now.

**Comment by Hotshot5000** [comment]
Yep. It's working now. Thanks!
