### ISSUE TITLE
build_ogre_macOS.sh fails with ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by Hotshot5000** [OGRECave/ogre-next#303]
#### System Information
- Ogre Version: latest commit
- Operating System / Platform: MacOS 12.3 / Macbook Pro M1
- RenderSystem: Metal
- GPU: M1

#### Detailled description
ogredeps get compiled for macOS not iOS but somehow ogre-next cannot link to libFreeImage

**Comment by Hotshot5000** [comment]
file libFreeImage.a 
libFreeImage.a: Mach-O universal binary with 2 architectures: [arm64:current ar archivecurrent ar archive] [x86_64]
libFreeImage.a (for architecture arm64):	current ar archive
libFreeImage.a (for architecture x86_64):	current ar archive

Seems to contain the arm64 build...

**Comment by Hotshot5000** [comment]
Closed by mistake....

**Comment by Hotshot5000** [comment]
When building ogredeps for iOS it seems that the function is there:
nm libFreeImage.a | grep _png_init_filter
0000000000000000 T _png_init_filter_functions_neon
00000000000069c8 t _png_init_filter_functions
                 U _png_init_filter_functions_neon

**Comment by darksylinc** [comment]
I never tried to build macOS for arm64 / M1; and I don't have an M1 to test.

Regarding the missing functions, [ogre-next-deps/src/FreeImage/CMakeLists.txt](https://github.com/OGRECave/ogre-next-deps/blob/master/src/FreeImage/CMakeLists.txt) chooses between ARM/SSE optimizations based on iOS setting:

```cmake
if( CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64" OR OGRE_BUILD_PLATFORM_APPLE_IOS )
	set( FreeImage_SOURCES ${FreeImage_SOURCES}
		Source/LibPNG/arm/arm_init.c
		Source/LibPNG/arm/filter_neon_intrinsics.c
	)
else()
	set( FreeImage_SOURCES ${FreeImage_SOURCES}
		Source/LibPNG/intel/filter_sse2_intrinsics.c
		Source/LibPNG/intel/intel_init.c
	)
endif()
```
Which is obviously wrong for native M1.

**Comment by Hotshot5000** [comment]
if( CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64" OR CMAKE_SYSTEM_PROCESSOR STREQUAL "arm64" OR OGRE_BUILD_PLATFORM_APPLE_IOS )

seems to do the trick.
But the samples don't get built as there is no storyboard for macOS just for iOS and I am not sure it can simply be reused.
Right now I will go back to iOS, macOS was just a test for now.

**Comment by Hotshot5000** [comment]
Added
if( NOT APPLE AND NOT OGRE_BUILD_PLATFORM_APPLE_IOS AND NOT ANDROID )
to line 13 in Samples/2.0/CMakeLists.txt

And then forced a build for SDL by adding
if (APPLE AND NOT OGRE_BUILD_PLATFORM_APPLE_IOS)
  option(OGREDEPS_BUILD_SDL2 "Build SDL2 dependency" TRUE)
endif ()
before line 10 in ogre-next-deps/src/CMakeLists.txt

But SDL would throw an error trying to move some SDL.dll which makes no sense. I noticed that the dylib was available though but could not get over the SDL build error so I forced Ogre to generate cmake anyway.

In the project I SDL.h not found everywhere so I hardcoded the path and now I got:
https://imgur.com/a/Ekkmw4s
running reasonably well on a M1 macbook.

Unfortunately I cannot capture GPU frames in this mode for whatever reason so the whole exercise was pointless as capturing GPU frames was the whole point.

**Comment by darksylinc** [comment]
Capturing frames should be possible.

Go to "Edit scheme" and in GPU API change it from autodetect to "Metal"

**Comment by Hotshot5000** [comment]
You're right. Now it's working. Why didn't it detect it as Metal automatically? It does that on Metal samples for both iOS and macOS... Weird.
Anyway, thanks. It now seems to work.
If you remember sometimes last year I was working on RayTraced shadows for Vulkan. Other projects got higher priority and had to stop.
But now I think I will try again this time on Metal on macOS (macbook is my primary work laptop these days).

I will also look into the whole macOS build these days and create a PR if I get to the bottom of why SDL isn't building correctly and why its headers aren't included in the XCode generated project.

**Comment by darksylinc** [comment]
Thanks! For SDL2 we recommend using brew because I couldn't get it working when built from scratch from source. If you manage to solve that it'd be great!

You probably know these tips already, we have Metal debugging [tips in the forum ](https://forums.ogre3d.org/viewtopic.php?t=95292)

**Comment by Hotshot5000** [comment]
I think this is done here. Thank you for your support!
