### ISSUE TITLE
 How to generate mipmap for a PNG or JPG image

### ISSUE THREAD

**Issue by 36yang** [OGRECave/ogre-next#331]
In order to solve the problem of flickering in distant images, I want to generate mipmaps for some images, but it seems useless to call the setnummipmaps method of the texturegpu class directly before the scene is created. Moreover, the default loaded image does not use the textureflags:: allowautomipmaps flag. When I add this flag when I load the image, it even causes a crash.

Therefore, I don't know how to generate mipmap for the image in the right way.

**Comment by darksylinc** [comment]
Hi, textures loaded from disk normally are already having automatic mipmap generation.

Can you post some code of how you're loading the textures?

**Comment by 36yang** [comment]
My texture was loaded  by HlmsJsonUnlit::loadTexture() function,  There ,the textureFlags has not use the textureflags:: allowautomipmaps flag.  if I add the flag, It may crashed.

**Comment by darksylinc** [comment]
Then the texture should already be mipmapped (thanks to the [TypeGenerateDefaultMipmaps](https://github.com/OGRECave/ogre-next/blob/603a55155f8cd434e09d5f2d965e3e8dbf3304ec/OgreMain/include/OgreTextureFilters.h#L64)  filter).

The allowautomipmaps is in case you need to generate mipmaps every frame (e.g. for RenderTextures).

You can check the mipmaps in RenderDoc. Perhaps the sampler is not using trilinear mipmap filtering?

**Comment by 36yang** [comment]
I have tried all texture filtering methods.

120 lines in the loadtexture() function of ogrehlmsjsonunlit.cpp

texture = mTextureManager->createOrRetrieveTexture(

textureName, aliasName, GpuPageOutStrategy::Discard, textureFlags, TextureTypes::Type2D,

resourceGroup );


The filters parameter is not passed, so this uses the default value of 0

**Comment by darksylinc** [comment]
Hi!

I added HlmsUnlit::setDefaultGenerateMipmaps to control this behavior. Also each JSON material can override the default behavior.

The reason behind this functionality is that Unlit sometimes you don't want it to generate mipmaps (e.g. GUI code) while other times you want to (e.g. particle FXs).
