### ISSUE TITLE
FindOgre missing functionality OGRE-Next pkg-config.

### ISSUE THREAD

**Issue by dermont123** [OGRECave/ogre-next#346]
Linux/ Ubuntu

OgreNext not found using FindOgre and pkg-config on local OgreNext installation.
[findogre.diff.zip](https://github.com/OGRECave/ogre-next/files/9921057/findogre.diff.zip)

**Comment by darksylinc** [comment]
Thanks for the patch! [Added](https://github.com/OGRECave/ogre-next/commit/491d37df15c048cd4757cd57d3091cec7c255fc5). Though looking "OGRE-Next" takes precedence over "OGRE".

Cheers!
