### ISSUE TITLE
Warning/Error OgreAAbb bitwise '&' with boolean operands

### ISSUE THREAD

**Issue by dermont123** [OGRECave/ogre-next#354]
clang version 15.0.6  
gcc version 12.2.1 

Ogre-Next master, Linux build (gcc 12.2.1) displays  the following warning on nearly every line build, the build completes:

`
(warning/error): use of bitwise '&' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
cast one or both operands to int to silence this warning
at OgreAabb.inl lines 109 to 111
`

Ogre-Next master, Android arm64-v8a build (clang 15.0.6) fails with same error as above.

**Comment by darksylinc** [comment]
Silenced the warning. This should be fixed now.
