### ISSUE TITLE
Forward 3D in Orthographic rendering broken

### ISSUE THREAD

**Issue by al2950** [OGRECave/ogre-next#36]
#### System Information
- Ogre Version: :2.2: 
- Operating System / Platform: :Windows (7 & 8): 
- RenderSystem: :dx11, assume others, but not tested:
- GPU: :GTX 980:

#### Detailled description
It would appear forward 3d things, eg lights, decals etc are broken when using Orthographic rendering. I have only been able to test up to the last revision on bitbucket, but has been broken for a very long time. Earliest revision I have tested is [ea7f397](https://bitbucket.org/sinbad/ogre/commits/ea7f3973568501a1458162238f502adae86a5e62)

Will continue to look in to it, after I have migrated to Github branches

**Comment by darksylinc** [comment]
I don't see a reason why this wouldn't be able to work. It's almost certainly a bug and not an algorithm limitation.

Probably a camera function we rely on for performing frustum culling in C++ doesn't produce the output we expect

**Comment by darksylinc** [comment]
Directly related forum discussion:
https://forums.ogre3d.org/viewtopic.php?p=546396

**Comment by darksylinc** [comment]
5 years later, this bug is finally fixed :smile:
