### ISSUE TITLE
PBR Discussion

### ISSUE THREAD

**Issue by darksylinc** [OGRECave/ogre-next#361]
@dyunchik [commented](https://github.com/OGRECave/ogre-next/pull/357#pullrequestreview-1297220984):

> [Commit "Fix Schlick fresnel is used instead of F0 as a multiplier to pre-comp" is wrong!](https://github.com/OGRECave/ogre-next/pull/357/files/9f26f523b813b1eebdc069b2575a598c3426a0aa)
> We have to use fresnelS - it takes in account pixelData.NdotV, but pixelData.F0 does not.
> 
> Correct code should be following:
```
midf3 Rs = pixelData.envColourS * pixelData.specular.xyz * ( fresnelS * make_float_fresnel( envBRDF.x ) + make_float_fresnel( envBRDF.y ) );
```

> Dielectric reflections depend on the NdotV. Indeed, after this commit all our reflected materials become flat and unrealistic.

I have to admit I am also uneasy with that particular change, since `fresnelS` depends on `F0`, but is dynamic per pixel. While F0 is constant, making look more 'dull' or 'flat'.

This change was done because according to @TaaTT4 it makes it look more similar to how other engines and DCC (Digital Content Creation) tools work.

We have several options:

1. Leave it with F0
2. Go back to `fresnelS`
3. Add `industry compatible` mode that can toggle between both (and possibly any other slight variations)

@TaaTT4 any comments?

**Comment by darksylinc** [comment]
OK so I'm gonna post what Eugene sent me. Which I didn't see until today:

> Commit has link to https://github.com/JoeyDeVries/LearnOpenGL/blob/master/src/6.pbr/2.2.1.ibl_specular/2.2.1.pbr.fs#L134
>
> and referenced code does
```cpp
F0 = mix(F0, albedo, metallic);
vec3 F    = fresnelSchlick(max(dot(H, V), 0.0), F0); 
vec3 specular = prefilteredColor  (F  brdf.x + brdf.y);
```
> i.e. F is semantically close to fresnelS in Ogre code 'before

> 4.4.3 Fresnel (specular F)
>
> The Fresnel effect plays an important role in the appearance of physically based materials. This effect models the fact that the amount of light the viewer sees reflected from a surface depends on the viewing angle. Large bodies of water are a perfect way to experience this phenomenon, as shown in figure 10. When looking at the water straight down (at normal incidence) you can see through the water. However, when looking further out in the distance (at grazing angle, where perceived light rays are getting parallel to the surface), you will see the specular reflections on the water become more intense.
>
> https://google.github.io/filament/Filament.html#materialsystem/dielectricsandconductors
> 
> also
>
> https://cginterest.com/wp-content/uploads/2021/01/210107_terragen_4_5_specmodels_v2_Dielectric_FrontLit_Socials-1024x916.jpg


@TaaTT4 also replied on his end:

>  as I wrote in the commit message, LearnOpenGL seems to be the only one using fresnelS: https://github.com/JoeyDeVries/LearnOpenGL/blob/master/src/6.pbr/2.2.1.ibl_specular/2.2.1.pbr.fs#L134 (F is equal to https://github.com/JoeyDeVries/LearnOpenGL/blob/master/src/6.pbr/2.2.1.ibl_specular/2.2.1.pbr.fs#L66)
>
> Filament uses F0: https://github.com/google/filament/blob/main/shaders/src/light_indirect.fs#L126 (the mix is due to the fact that they use energy compensation)
>
> Also in the documentation they still use F0: https://google.github.io/filament/Filament.html#listing_iblevaluation (this listing is before they introduce the concept of energy compensation in the next paragraph)
> Sebastian Lagarde seems to do the same in its document (https://seblagarde.files.wordpress.com/2015/07/course_notes_moving_frostbite_to_pbr_v32.pdf): see listing 24 at page 70
>
> I cannot find the shader code at the moment from UE4 (I need more time to dig better), but I'm pretty sure they do the same too

> the visual difference between fresnelS (...) and F0 (..) is appreciable only in roughness and metalness around 0. with fresnelS they have like an halo at the edges


So it seems that everyone is in agreement; except that some people prefer one version and other people prefer _the other_ version.

I suppose the only solution here I see is to add a toggle. It's probably gonna be called "industry_compatible"; and off by default.

The idea would be that "industry_compatible" we don't stray too much from industry; but when it's on; we get much more strict.

Is that ok for everyone?

**Comment by dyunchik** [comment]
Yep, it's really better to have the industry_compatible toggle.

**Comment by darksylinc** [comment]
I added the [industry compatible](https://github.com/OGRECave/ogre-next/commit/37361505e56414015c04ba2995860cf7b26539d8) toggle.

In the future it may become an enum, but for now a bool will do.

I also changed how we are handling JSON materials since the PBR PR changes.

If a user loads a JSON material meant for OgreNext 2.2 or 2.3, it should look as close as possible as it did in 3.0

It didn't make sense that one needed to call `HlmsPbs::setDefaultBrdfWithDiffuseFresnel( true )` first. Specially because if you don't dig through the documentation, you may not even know you had to do that.

**Comment by TaaTT4** [comment]
Sorry for the late reply, but I wasn't at home in these days.
As Matias quoted from a private conversation we had, the goal of my changes to PBR was to mimic the commercial tools because the artists in the studio aiming for that visual appearance. I've then focused more on replicating the code than being mathematically correct. And, as I said to Mathias (and as Eugene also notes), LearnOpenGL Is the only One using Schlick fresnel instead of F0.
Please note that in my tests and comparisons the visual difference between using Schlick fresnel and F0 is small and noticeable at grazing angles just for materials with roughness and metalness close to 0. As I written in the forum, the weighting with `1 - fresnelS` of the diffuse lighting component is what made OGRE rendering diverge the most from commercial tools.

**Comment by darksylinc** [comment]
After careful study I believe I found the reason why other engines chose `1 - F0` instead of `1 - fresnelS`:

As everyone here found out, with `1 - fresnelS` you get a bright halo at grazing angles when F0 is low and roughness is high:

`1 - fresnelS`
![image](https://user-images.githubusercontent.com/3395130/219904541-a6490c37-4dc0-4fbd-b078-16ece9cdd5bc.png)

vs

`1 - F0`
![image](https://user-images.githubusercontent.com/3395130/219904537-afbdd28f-5758-4d1e-b055-5147f6f8048d.png)

Check top left.

Although `1 - fresnelS` is probably "more correct", it also requires far more accuracy in the GI probes, otherwise it tends to overbrighten or perform light leaks.

Although it's possible that the game Forsaken has many problems and could be using 1 - F0, it looks like this is the case of 1 - fresnelS:
https://twitter.com/newincpp/status/1626916531274760195

![image](https://user-images.githubusercontent.com/3395130/219904662-154a975a-7504-48d1-93f5-c3e5f29a88a3.png)

We can see **the ceiling** has blue tint from the sky. In reality this shouldn't happen because it's occluded, and with ray/pathtracing it would look correct.

However if using basic probes (and/or low probe count) the GI will pick up the horizon and perform this kind of overbrighten... which can be simply be "patched" by using `1 - F0`.

You still have the problem that at low roughness values the reflection is wrong, but due to how our brain works, we don't notice as easily that it is wrong.
