### ISSUE TITLE
The problem with starting even examples

### ISSUE THREAD

**Issue by OlShel** [OGRECave/ogre-next#364]
#### System Information
- Ogre Version: 2.3.0 
- Operating System / Platform: Win10 
- RenderSystem: :grey_question:
- GPU: nVidia Quadro 3000M

Hello!
The application I'm working on uses Ogre. On one of the machines the Ogre scene is not displaying, and there are no errors or warnings or anything. I decided to check the test samples from the release archive and they won't run either. Running, for example, Sample_Tutorial02_VariableFramerate.exe, gives the short log I attached. 
Is it possible that this is a problem in the videocard? I couldn't find any confirmation or denial of nVidia Quadro support.
Let me know if you need additional info.
Best regards.

**Comment by AllianceDarkSylinc** [comment]
Hi!

Judging the Ogre log, it looks like Ogre crashed right after finding out Vulkan has drivers BUT no Vulkan-supported GPU.

As a workaround you can disable/comment out the Vulkan RenderSystem from Plugins.cfg and it should start working.

Are you able to get a callstack right when the crash happens to know what went wrong so we can fix it?
