### ISSUE TITLE
I did not find any way to cancel the gamma algorithm for textures in the API. May I ask how to cancel it

### ISSUE THREAD

**Issue by chentiannan** [OGRECave/ogre-next#405]
I did not find any way to cancel the gamma algorithm for textures in the API. May I ask how to cancel it

**Comment by darksylinc** [comment]
Hi!

# Disabling sRGB on Framebuffer

When initializing OgreNext call:

```
rs->setConfigOption( "sRGB Gamma Conversion", "Yes" );
Ogre::ConfigOptionMap &cfgOpts = rs->getConfigOptions();
params.insert( std::make_pair( "gamma", cfgOpts["sRGB Gamma Conversion"].currentValue ) );
mRenderWindow = Ogre::Root::getSingleton().createRenderWindow(
    windowTitle,                                                      //
    static_cast<uint32_t>( width ), static_cast<uint32_t>( height ),  //
    fullscreen, &params );
```

# Disabling sRGB on all loaded textures

Set `TextureGpuManager::mIgnoreSRgbPreference = true`

**Comment by chentiannan** [comment]
I don't know if it's a bug, but after setting the parameters, I still encountered gamma when rendering a solid color image into the texture. The specific situation is as follows:
![image](https://github.com/OGRECave/ogre-next/assets/37989848/7cd2cb67-3915-4791-95ca-83264d2ea74b)

The log output is as follows
![image](https://github.com/OGRECave/ogre-next/assets/37989848/fa6e73b5-c92d-40eb-81f5-870e262be358)

**Comment by darksylinc** [comment]
Hi!

1. Set mIgnoreSRgbPreference as early as possible. To be sure and rule this out, do it right after calling createRenderWindow()
2. The value RGB `255 255 255` maps to `255 255 255` even in sRGB space. If you see the value `255 255 255` mapping to `209 209 209` then there is something else going on.

**Comment by 36yang** [comment]
The  Gamma convert was happened when  a RenderTexture used as a media texture;
How can I avoid this Gamma convert?

**Comment by chentiannan** [comment]
> Hi!
> 
> How are you creating the RenderTexture? If created via Compositor, you can either explicitly request a pixel format or use the pixel format of the connected output (and it's a matter of determining that connected RenderTarget's format), if created via code, you're the one who explicitly selects the pixel format.

I think this is a bug when I use TextureGpuManager:: mIgnoreSRgbPreference=true and specify a texture format when creating a rendered texture, but the output of this rendered texture is not 1:1

**Comment by chentiannan** [comment]
When I use TextureFlags:: RenderToTexture, my Ogre:: PixelFormatGpu is PFG_ RGBA8_ UNORM_ SRGB, I used a D3D shared texture to fill the data. After calling RenderOneFrame, my colors were mapped from B [000], G [255], R [000], A [255] to B [000], G [209], R [000], A [255]. If you have any ideas, please let me know

**Comment by 36yang** [comment]
> Hi!
> 
> How are you creating the RenderTexture? If created via Compositor, you can either explicitly request a pixel format or use the pixel format of the connected output (and it's a matter of determining that connected RenderTarget's format), if created via code, you're the one who explicitly selects the pixel format.

I create the RenderTexture by code, and use the pixel format of PFG_ RGBA8_ UNORM_ SRGB,  The mainWindow was gamma correct on, because I use the Hlms of PBR,  but the RenderTexture was use to render video framebuffer. So it can't be gamma corrected. but when I then use then rendertexture as a media texutre of a. lowlevel material,  The sampled value was gamma corrected, like, [255] to [209],   And I can't find a method to control it  to not  convert.

**Comment by darksylinc** [comment]
Hi!

> When I use TextureFlags:: RenderToTexture, my Ogre:: PixelFormatGpu is PFG_ RGBA8_ UNORM_ SRGB, I used a D3D shared texture to fill the data. After calling RenderOneFrame, my colors were mapped from B [000], G [255], R [000], A [255] to B [000], G [209], R [000], A [255]. If you have any ideas, please let me know

The format must `PFG_ RGBA8_ UNORM` instead of `PFG_ RGBA8_ UNORM_ SRGB`, otherwise it IS gamma what you are requesting (that's what sRGB is).

**Comment by chentiannan** [comment]
> Hi!
> 
> > When I use TextureFlags:: RenderToTexture, my Ogre:: PixelFormatGpu is PFG_ RGBA8_ UNORM_ SRGB, I used a D3D shared texture to fill the data. After calling RenderOneFrame, my colors were mapped from B [000], G [255], R [000], A [255] to B [000], G [209], R [000], A [255]. If you have any ideas, please let me know
> 
> The format must `PFG_ RGBA8_ UNORM` instead of `PFG_ RGBA8_ UNORM_ SRGB`, otherwise it IS gamma what you are requesting (that's what sRGB is).

I use the synthesizer to associate my material texture, and then sample the color from the shader, and the color value changes. Does the synthesizer have related settings or some parameters need to be set in the synthesizer script?

**Comment by darksylinc** [comment]
> I use the synthesizer

I'm afraid I have no idea what you mean by 'synthesizer' :face_with_spiral_eyes: 

Are you able to provide a small repro (preferably by modifying one of the current samples) so I understand what you're doing and what's wrong?

Cheers

**Comment by chentiannan** [comment]
> > I use the synthesizer
> 
> I'm afraid I have no idea what you mean by 'synthesizer' 😵‍💫
> 
> Are you able to provide a small repro (preferably by modifying one of the current samples) so I understand what you're doing and what's wrong?
> 
> Cheers

The problem is solved, it is caused by the UV addressing of the sampler, it has nothing to do with gamma, only need to open gamma in the window
