### ISSUE TITLE
Rename FeatureSummary.cmake

### ISSUE THREAD

**Issue by gentili** [OGRECave/ogre-next#406]
- Ogre Version: 2.3.1

When I include ogre-next in my projects vcpkg.json I get the following error during the vcpkg build step for ogre-next:

```
CMake Error at C:/Users/gentili/source/repos/mastercontrolproductions/concursion/out/build/x64-Debug/vcpkg_installed/x64-windows/share/sdl2/SDL2Config.cmake:4 (set_package_properties):
  Unknown CMake command "set_package_properties".
Call Stack (most recent call first):
  C:/Users/gentili/source/repos/vcpkg/scripts/buildsystems/vcpkg.cmake:855 (_find_package)
  CMake/Dependencies.cmake:280 (find_package)
  CMakeLists.txt:253 (include)
```

This seems to be the same collision called out in
https://github.com/OGRECave/ogre/issues/2381
and solved by
https://github.com/OGRECave/ogre/pull/2383/commits/e34ef06bb0d49ce847efe3a80ebe01c9762ea0b1

**Comment by darksylinc** [comment]
Thanks! [This fix](https://github.com/OGRECave/ogre-next/commit/8de8c1011ab3305b8d5deb9e37f9b5d3ed370a66) will be included in the 3.0 release.

I'm afraid ghanging this for 2.3.x could rock the boat too much.
