### ISSUE TITLE
Dangle pointer in map BarrierSolver::mResourceStatus leads to the false positive assert in BarrierSolver::debugCheckDivergingTransition

### ISSUE THREAD

**Issue by StoyanovVlad** [OGRECave/ogre-next#416]
#### System Information
- Ogre Version: :grey_question: 2.2
- Operating System / Platform: :grey_question: Android 13 
- RenderSystem: :grey_question: Vulkan
- GPU: :grey_question: 

#### Detailled description
Before creating OgreRenderWindow I create and load texture and setup it in HlmsPbsDatablock, during loading my texture the func GenerateHwMipmaps::_executeSerial() is called where  temporary texture with name "___tempMipmapTexture" is created and destroyed at the end of func GenerateHwMipmaps::_executeSerial(). During destroying temporary texture in dtor this texture is added to the BarrierSolver **which become a dangle pointer right after exiting dtor**.  After that I create OgreRenderWindow, during this call texture with "RenderWindow" is created, and **if memory for this texture was allocated at the place where dangle pointer in BarrierSolver points to** the pointer automatically becomes valid, what is wrong, because no adding was done and later assert will be triggered.

1)Here is adding texture to the Barrier
<img width="1854" alt="Screenshot 2023-09-11 at 23 53 57" src="https://github.com/OGRECave/ogre-next/assets/10288328/e167bee0-d741-43b8-82cd-02ed77b90f47">

2)Here is the dangle pointer before creating  texture "RenderWindow"
<img width="1848" alt="Screenshot 2023-09-11 at 23 55 47" src="https://github.com/OGRECave/ogre-next/assets/10288328/799ecb9e-2bee-453e-bcf7-db1532a91a41">

3)Here is stop right after allocating and pointer become valid, but no adding was done to the Barrier
<img width="1842" alt="Screenshot 2023-09-11 at 23 56 13" src="https://github.com/OGRECave/ogre-next/assets/10288328/912ea910-8f15-4ca8-ad07-9c135f3da130">

4)Here is my code detects dangle pointer to stop
<img width="1848" alt="Screenshot 2023-09-11 at 23 56 32" src="https://github.com/OGRECave/ogre-next/assets/10288328/29ae798a-540b-4a2f-828c-b7fdc2c23d68">

5)Here is the triggered assert and texture which trigger  the assert
<img width="1422" alt="Screenshot 2023-09-11 at 23 56 53" src="https://github.com/OGRECave/ogre-next/assets/10288328/c47e7839-e25c-4cfa-9c1b-854835996819">
<img width="1809" alt="Screenshot 2023-09-11 at 23 57 55" src="https://github.com/OGRECave/ogre-next/assets/10288328/ec080c35-bcc7-423a-a0ed-fe8f0e46dfec">

**Comment by StoyanovVlad** [comment]
Suggested fix - selected lines in screenshot
<img width="1669" alt="Screenshot 2023-09-12 at 00 22 44" src="https://github.com/OGRECave/ogre-next/assets/10288328/95d8f08b-98df-4a3a-964a-c33684de0e72">

**Comment by darksylinc** [comment]
Hi!

First, I congratulate you for such high quality ticket. I wish there were more like yours.

> After that I create OgreRenderWindow, during this call texture with "RenderWindow" is created, and if memory for this texture was allocated at the place where dangle pointer in BarrierSolver points to the pointer automatically becomes valid, what is wrong, because no adding was done and later assert will be triggered.

Ah, basically the memory address got reused for an unrelated allocation. Yikes!

> Supposed fix - selected lines in screenshot

Funny enough `TextureGpuManager::destroyTextureImmediate` already calls `barrierSolver.textureDeleted` but unfortunately it gets added again when it shouldn't have.

Does this alternate solution fix the problem?

```cpp
diff --git a/RenderSystems/Vulkan/src/OgreVulkanQueue.cpp b/RenderSystems/Vulkan/src/OgreVulkanQueue.cpp
index 97b805e3f7..f6d4cfa874 100644
--- a/RenderSystems/Vulkan/src/OgreVulkanQueue.cpp
+++ b/RenderSystems/Vulkan/src/OgreVulkanQueue.cpp
@@ -1064,10 +1064,14 @@ namespace Ogre
         if( mEncoderState == EncoderCopyOpen )
         {
             bool needsToFlush = false;
+            bool mustRemoveFromBarrier = false;
             TextureGpuDownloadMap::const_iterator itor = mCopyDownloadTextures.find( texture );
 
             if( itor != mCopyDownloadTextures.end() )
+            {
                 needsToFlush = true;
+                mustRemoveFromBarrier = true;
+            }
             else
             {
                 FastArray<TextureGpu *>::const_iterator it2 =
@@ -1085,6 +1089,14 @@ namespace Ogre
                 OGRE_ASSERT_LOW( texture->mCurrLayout == VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL ||
                                  texture->mCurrLayout == VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL );
                 endCopyEncoder();
+
+                if( mustRemoveFromBarrier )
+                {
+                    // endCopyEncoder() just called solver.assumeTransition() on this texture
+                    // but we're destroying the texture. Remove the dangling pointer.
+                    BarrierSolver &solver = mRenderSystem->getBarrierSolver();
+                    solver.textureDeleted( texture );
+                }
             }
         }
     }
```

>  After that I create OgreRenderWindow

**Unrelated to this bug:** OgreNext historically was written when D3D7 and (pre 2.0) OpenGL were around; and it has the unfortunate assumption that the at least one RenderWindow must be the first thing created before anything else (and the last thing to be destroyed).

Because Vulkan & Metal no longer have this restriction; it may just work (i.e. creating GPU resources before creating the Window).

Personally I recommend that "just in case", if possible, you create the RenderWindow first to ensure everything is properly initialized.

**Comment by StoyanovVlad** [comment]
Hi! Thank you for your quick reply. Yes, your alternate solution fixes the problem as well.

**Comment by darksylinc** [comment]
[Done](https://github.com/OGRECave/ogre-next/commit/4efe05799543f96740f5a3559c1ba1eeec944839)! Thanks for the report!
