### ISSUE TITLE
compile ogre-next from source along side ogre.

### ISSUE THREAD

**Issue by talregev** [OGRECave/ogre-next#419]
As a vcpkg user, I would like to compile ogre-next along side ogre. The problem is, that when I compile it from source it have the same name as original ogre lib. Can you differentiate this library lib binary file name from ogre? Maybe as you ship it as ogre-next? Similar to your repo name.

**Comment by darksylinc** [comment]
Hi!

See #259 

OgreNext 2.3 added the [OGRE_USE_NEW_PROJECT_NAME](https://github.com/OGRECave/ogre-next/blob/651759e389fd55f8d0f1e4602aa3c776e67237ea/CMakeLists.txt#L54C8-L54C33) CMake option to address this issue.

The roadmap is as follows:

- OgreNext 3.0 OGRE_USE_NEW_PROJECT_NAME is off by default.
- OgreNext 4.0 OGRE_USE_NEW_PROJECT_NAME is on by default.
- OgreNext 5.0 OGRE_USE_NEW_PROJECT_NAME is marked as deprecated.
- OgreNext 6.0 will not ship with OGRE_USE_NEW_PROJECT_NAME.

**Comment by talregev** [comment]
Can you release version 2.3?

**Comment by talregev** [comment]
On version 2.3.1 is still not there:
https://github.com/OGRECave/ogre-next/blob/v2.3.1/CMakeLists.txt

Can you release 2.3.2?

**Comment by talregev** [comment]
Until you don't release a new version that contain this fix, the issue still remain. Please open the issue.

**Comment by darksylinc** [comment]
Sounds fair.

**Comment by darksylinc** [comment]
[2.3.2 has been released](https://github.com/OGRECave/ogre-next/releases/tag/v2.3.2).
Closing.

Tomorrow I'll be updating the main website.
We'll soon be making a 3.0 release too; if you have [naming candidates](https://forums.ogre3d.org/viewtopic.php?p=555420), they're welcome.

Cheers
