### ISSUE TITLE
rename OGER to OGER-Next in pc files.

### ISSUE THREAD

**Issue by talregev** [OGRECave/ogre-next#420]
#### System Information
- Ogre Version: 2.3.2 
- Operating System / Platform: wsl ubuntu 22.04 with vcpkg
- RenderSystem: :grey_question: I don't know
- GPU: AMD

#### Detailled description

I compile ogre-next 2.3.2 on vcpkg with the flag: `-DOGRE_USE_NEW_PROJECT_NAME=ON` to have the new name of ogre-next.
It compile successful with the new name on the libs. but the pc file didn't not update to the new name:
```
prefix=${pcfiledir}/../..
exec_prefix=${prefix}
libdir=${prefix}/lib
includedir=${prefix}/../include
plugindir=${libdir}/OGRE

Name: OGRE (static lib)
Description: Object-Oriented Graphics Rendering Engine
Version: 2.3.2
URL: http://www.ogre3d.org

Libs: "-L${libdir}" "-L${plugindir}" -lOgreMainStatic_d -lpthread -lboost-thread-mt -lfreeimage
Requires: freetype2, zziplib, x11, xt, xaw7, gl
Cflags: "-I${includedir}" "-I${includedir}/OGRE" -pthread
```

it should change the name the include folder and the linkage flags:
```
plugindir=${libdir}/OGRE -> plugindir=${libdir}/OGRE-Next
Name: OGRE (static lib) -> Name: OGRE-Next (static lib)
 -lOgreMainStatic_d ->  -lOgreNextMainStatic_d
-I${includedir}/OGRE -> -I${includedir}/OGRE-Next
```

#### Callstack

Not relevant. not in run time.

**Comment by talregev** [comment]
It coming from here:
https://github.com/OGRECave/ogre-next/blob/master/CMake/Templates/OGREStatic.pc.in
Is it not update by purpose? 
I can make a patch on vcpkg side.

**Comment by talregev** [comment]
I think also here:
https://github.com/OGRECave/ogre-next/blob/491d37df15c048cd4757cd57d3091cec7c255fc5/RenderSystems/Direct3D11/CMakeLists.txt#L64

```
install(FILES ${HEADER_FILES} DESTINATION include/OGRE/RenderSystems/Direct3D11) ->
install(FILES ${HEADER_FILES} DESTINATION include/${OGRE_NEXT_PREFIX}/RenderSystems/Direct3D11)
```

**Comment by talregev** [comment]
Thank you!

**Comment by darksylinc** [comment]
Thank you for reporting it!

I'm planning on making a new 2.3 release to address this issue.
