### ISSUE TITLE
Is Ray Tracing and FSR/DLSS supported or planned?

### ISSUE THREAD

**Issue by HumanGamer** [OGRECave/ogre-next#465]
I haven't seen this mentioned anywhere. Is there currently support for Ray Tracing, and FSR/DLSS Upscaling and Frame Gen? If not, is this a planned feature? I didn't see any roadmap for the project to refer to.

**Comment by darksylinc** [comment]
**FSR/DLSS Upscaling and Frame Gen:** No. There have been no requests, and it would need us to generate velocity vectors, which is high maintenance and we don't have the resources for it.

**Ray Tracing:** It is planned, and user HotShot5000 has a WIP working implementation. But it's not a priority right now, unless someone is willing to finance it.

**Comment by HumanGamer** [comment]
sounds good, thank you
