### ISSUE TITLE
Sample_Tutorial_SSAO only works with no FSAA

### ISSUE THREAD

**Issue by cryham** [OGRECave/ogre-next#476]
#### System Information
- Ogre Version: 3.0.0
- Operating System / Platform: Debian 12
- RenderSystem: GLv3+
- GPU: AMD RX 6600 XT

#### Detailled description
Build from latest 3.0.0,
I'm, starting Sample_Tutorial_SSAO, works fine if I set 0 for FSAA.
If I set FSAA 2, 4 or 8 it is broken, SSAO does not work, it's textures are filled with just 1 value, and changing SSAO parameters (by keys) just makes the whole rendered screen darker or brighter.
I lost a day thinking there is something wrong with the C++ code or setup I did from that sample's .compositor and trying other combinations, but nope wasn't that.

#### Ogre.log
[Ogre SSAO FSAA 4.log](https://github.com/user-attachments/files/17692445/Ogre.SSAO.FSAA.4.log)

![Ogre SSAO FSAA 4](https://github.com/user-attachments/assets/5e29ea23-5637-4be2-a66d-229e8ea8ba4d)

Would be nice to know what to do with those RTT textures to get it working. I guess some resolve missing? Or maybe needs own node like in Refractions to have buffers resolved? OFC fix would be best.
There should be at least a NOTE in F1 help telling that it won't work with FSAA.

**Comment by darksylinc** [comment]
Fixed. Thanks!

**Comment by cryham** [comment]
Great thanks. I likely wouldn't figure this all out by myself.
