### ISSUE TITLE
MacOSx build fails with xcode 10 beta

### ISSUE THREAD

**Issue by crookedbard** [OGRECave/ogre-next#7]
#### System Information
- Ogre Version: 2.1 branch
- Operating System / Platform: macOSx
- RenderSystem: openGL3

#### Detailled description
I am building Ogre xcode project from source with such commands:
cmake -D OGRE_BUILD_RENDERSYSTEM_METAL=1 -D OGRE_USE_BOOST=0 -D OGRE_CONFIG_THREAD_PROVIDER=0 -D OGRE_CONFIG_THREADS=0 -D OGRE_BUILD_SAMPLES2=1 -D OGRE_UNITY_BUILD=1 -D OGRE_SIMD_NEON=0 -D OGRE_BUILD_TESTS=0 -D OGRE_SIMD_SSE2=0 -G Xcode ..

and I get GL3Plus errors

#### Ogre.log
In file included from /Users/dkr/Documents/Bitbucket/ogre/ogre2.1/RenderSystems/GL3Plus/src/windowing/OSX/OgreOSXCocoaContext.mm:29:
In file included from /Users/dkr/Documents/Bitbucket/ogre/ogre2.1/RenderSystems/GL3Plus/include/windowing/OSX/OgreOSXCocoaContext.h:31:
In file included from /Users/dkr/Documents/Bitbucket/ogre/ogre2.1/RenderSystems/GL3Plus/include/OgreGL3PlusContext.h:32:
In file included from /Users/dkr/Documents/Bitbucket/ogre/ogre2.1/RenderSystems/GL3Plus/include/OgreGL3PlusPrerequisites.h:80:
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers/gl3ext.h:187:77: error: expected function body after function declarator
GLAPI void APIENTRY glVertexAttribDivisorARB (GLuint index, GLuint divisor) OPENGL_DEPRECATED(10.6, 10.14);
                                                                            ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers/gl3ext.h:249:104: error: expected function body after function declarator
GLAPI void APIENTRY glLabelObjectEXT (GLenum type, GLuint object, GLsizei length, const GLchar *label) OPENGL_DEPRECATED(10.6, 10.14);
                                                                                                       ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers/gl3ext.h:250:119: error: expected function body after function declarator
GLAPI void APIENTRY glGetObjectLabelEXT (GLenum type, GLuint object, GLsizei bufSize, GLsizei *length, GLchar *label) OPENGL_DEPRECATED(10.6, 10.14);
                                                                                                                      ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers/gl3ext.h:259:81: error: expected function body after function declarator
GLAPI void APIENTRY glInsertEventMarkerEXT (GLsizei length, const char *marker) OPENGL_DEPRECATED(10.6, 10.14);
                                                                                ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers/gl3ext.h:260:79: error: expected function body after function declarator
GLAPI void APIENTRY glPushGroupMarkerEXT (GLsizei length, const char *marker) OPENGL_DEPRECATED(10.6, 10.14);
                                                                              ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers/gl3ext.h:261:48: error: expected function body after function declarator
GLAPI void APIENTRY glPopGroupMarkerEXT (void) OPENGL_DEPRECATED(10.6, 10.14);
                                               ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers/gl3ext.h:271:69: error: expected function body after function declarator
GLAPI void APIENTRY glDepthBoundsEXT (GLclampd zmin, GLclampd zmax) OPENGL_DEPRECATED(10.6, 10.14);
                                                                    ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers/gl3ext.h:307:47: error: expected function body after function declarator
GLAPI void APIENTRY glFlushRenderAPPLE (void) OPENGL_DEPRECATED(10.6, 10.14);
                                              ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers/gl3ext.h:308:48: error: expected function body after function declarator
GLAPI void APIENTRY glFinishRenderAPPLE (void) OPENGL_DEPRECATED(10.6, 10.14);
                                               ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers/gl3ext.h:309:40: error: expected function body after function declarator
GLAPI void APIENTRY glSwapAPPLE (void) OPENGL_DEPRECATED(10.6, 10.14);
                                       ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers/gl3ext.h:319:94: error: expected function body after function declarator
GLAPI GLenum APIENTRY glObjectPurgeableAPPLE (GLenum objectType, GLuint name, GLenum option) OPENGL_DEPRECATED(10.6, 10.14);
                                                                                             ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers/gl3ext.h:320:96: error: expected function body after function declarator
GLAPI GLenum APIENTRY glObjectUnpurgeableAPPLE (GLenum objectType, GLuint name, GLenum option) OPENGL_DEPRECATED(10.6, 10.14);
                                                                                               ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers/gl3ext.h:321:111: error: expected function body after function declarator
GLAPI void APIENTRY glGetObjectParameterivAPPLE (GLenum objectType, GLuint name, GLenum pname, GLint *params) OPENGL_DEPRECATED(10.6, 10.14);
                                                                                                              ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers/gl3ext.h:339:96: error: expected function body after function declarator
GLAPI void APIENTRY glTextureRangeAPPLE (GLenum target, GLsizei length, const GLvoid *pointer) OPENGL_DEPRECATED(10.6, 10.14);
                                                                                               ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers/gl3ext.h:340:99: error: expected function body after function declarator
GLAPI void APIENTRY glGetTexParameterPointervAPPLE (GLenum target, GLenum pname, GLvoid **params) OPENGL_DEPRECATED(10.6, 10.14);
                                                                                                  ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers/gl3ext.h:353:47: error: expected function body after function declarator
GLAPI void APIENTRY glTextureBarrierNV (void) OPENGL_DEPRECATED(10.6, 10.14);
                                              ^
/Users/dkr/Documents/Bitbucket/ogre/ogre2.1/RenderSystems/GL3Plus/src/windowing/OSX/OgreOSXCocoaContext.mm:56:13: warning: 'copyAttributesFromContext:withMask:' is deprecated: first deprecated in macOS 10.8 [-Wdeprecated-declarations]
                [cloneCtx copyAttributesFromContext:mNSGLContext withMask:0];
                          ^
In file included from /Users/dkr/Documents/Bitbucket/ogre/ogre2.1/RenderSystems/GL3Plus/src/windowing/OSX/OgreOSXCocoaContext.mm:29:
In file included from /Users/dkr/Documents/Bitbucket/ogre/ogre2.1/RenderSystems/GL3Plus/include/windowing/OSX/OgreOSXCocoaContext.h:32:
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSOpenGL.h:225:1: note: 'copyAttributesFromContext:withMask:' has been explicitly marked deprecated here
- (void)copyAttributesFromContext:(NSOpenGLContext *)context withMask:(GLbitfield)mask NS_DEPRECATED_MAC(10_0, 10_8);
^
1 warning and 16 errors generated.

**Comment by darksylinc** [comment]
I'm closing it since Ogre-Next is building with XCode 13 now.
