### ISSUE TITLE
Sample_IesProfiles doesn't work with D3D11 render system

### ISSUE THREAD

**Issue by TaaTT4** [OGRECave/ogre-next#70]
As the title says, `Sample_IesProfiles` works just with GL render system. If you launch it using D3D11 render system, you get this is the error (also see the attached [shader](https://github.com/OGRECave/ogre-next/files/4122622/100000000PixelShader_ps.hlsl.txt)):
```
Ogre: High-level program 100000000PixelShader_ps encountered an error during loading and is thus not supported.
OGRE EXCEPTION(-2147467259:RenderingAPIException): Cannot compile D3D11 high-level shader 100000000PixelShader_ps Errors:
D:\Development\SDK\OGRE\OGRE\build\x64\bin\Debug\100000000PixelShader_ps.hlsl(495,10): error X3004: undeclared identifier 'lightProfiles'
 in D3D11HLSLProgram::compileMicrocode at D:/Development/SDK/OGRE/OGRE/RenderSystems/Direct3D11/src/OgreD3D11HLSLProgram.cpp (line 569)
```

In addition, there's a memory leak at line 82 of `OgreLightProfiles.cpp`:
```
IesLoader *iesLoader = OGRE_NEW IesLoader( filename, dataStr.c_str() );
mIesData.push_back( iesLoader );
```
Content of `mIesData` is never destroyed.

**Comment by darksylinc** [comment]
Thanks! I've pushed a fix.
Could you verify it works?

Thanks

**Comment by TaaTT4** [comment]
Nope, it's fixed just the memory leak. I get the same shader compilation error as before.
Correct me if I'm wrong, but I believe that the issue isn't related to where `Texture2D lightProfiles` and `SamplerState lightProfilesSampler` are declared. I suspect it's caused by the fact that those variables aren't visible inside the body of `getPhotometricAttenuation` unless you pass them as parameters.

**Comment by darksylinc** [comment]
Fixed.

> Correct me if I'm wrong, but I believe that the issue isn't related to where Texture2D lightProfiles and SamplerState lightProfilesSampler are declared

You're wrong :rofl: 

Metal is the only language that doesn't allow global variables. There were 2 bugs: 1st, the textures were being declared too late. 2nd, bug the sampler had a typo
