### ISSUE TITLE
Bones switching to manual on memory cleanup

### ISSUE THREAD

**Issue by sgynn** [OGRECave/ogre-next#9]
#### System Information
- Ogre Version: 2.1 
- Operating System / Platform: Windows
- RenderSystem: DirextX11

#### Detailled description
When the bone memory manager cleanup is performed, the SkeletonInstance manual bones array becomes incorrect as it depends on the bone transform index which can change.
This causes some bones to randomly switch to manual mode causing problems.

**Comment by darksylinc** [comment]
This bug took a long time to fix, but it finally arrived.

Applied the fix to all branches (2.1,2.2, and 2.3 / aka master)
