### ISSUE TITLE
[Ogre-2.1] Compilation fails (OgrePVRTCCodec.cpp, OgreGrid2DPageStrategy.cpp, OgreGrid3DPageStrategy.cpp)

### ISSUE THREAD

**Issue by Yamakuzure** [OGRECave/ogre-next#90]
While working on a Gentoo ebuild for the first major Ogre 2.1 release (congrats on that!), I hit some compilation issues.

One question beforehand: I have to build with 
````
		-DOGRE_BUILD_COMPONENT_PROPERTY=no
		-DOGRE_BUILD_COMPONENT_RTSHADERSYSTEM=no
		-DOGRE_BUILD_RTSHADERSYSTEM_CORE_SHADERS=no
		-DOGRE_BUILD_RTSHADERSYSTEM_EXT_SHADERS=no
		-DOGRE_BUILD_COMPONENT_TERRAIN=no
		-DOGRE_BUILD_COMPONENT_VOLUME=no
		-DOGRE_BUILD_PLUGIN_CG=no
````
Are these just not ported, yet, or remnants in `CMakeLists.txt` that can be ignored?

## System
 * Gentoo Linux x86_64
 * cmake-3.17.1
 * gcc-9.3.0
 * mesa-20.0.5
 * Build for Intel-Iris

## Build Configuration
````
		-DOGRE_BUILD_COMPONENT_HLMS_PBS=yes
		-DOGRE_BUILD_COMPONENT_HLMS_PBS_MOBILE=no
		-DOGRE_BUILD_COMPONENT_HLMS_UNLIT=yes
		-DOGRE_BUILD_COMPONENT_HLMS_UNLIT_MOBILE=no
		-DOGRE_BUILD_COMPONENT_PAGING=yes
		-DOGRE_BUILD_COMPONENT_PLANAR_REFLECTIONS=yes
		-DOGRE_BUILD_COMPONENT_SCENE_FORMAT=yes
		-DOGRE_BUILD_PLATFORM_NACL=no
		-DOGRE_BUILD_RENDERSYSTEM_GL3PLUS=yes
		-DOGRE_BUILD_RENDERSYSTEM_GLES2=yes
		-DOGRE_BUILD_SAMPLES2=yes
		-DOGRE_BUILD_TESTS=yes
		-DOGRE_BUILD_TOOLS=yes
		-DOGRE_CONFIG_ALLOCATOR=1
		-DOGRE_CONFIG_ENABLE_FINE_LIGHT_MASK_GRANULARITY=yes
		-DOGRE_CONFIG_ENABLE_FREEIMAGE=yes
		-DOGRE_CONFIG_ENABLE_GL_STATE_CACHE_SUPPORT=yes
		-DOGRE_CONFIG_ENABLE_JSON=yes
		-DOGRE_CONFIG_MEMTRACK_DEBUG=no
		-DOGRE_CONFIG_MEMTRACK_RELEASE=no
		-DOGRE_CONFIG_THREADS=2
		-DOGRE_CONFIG_THREAD_PROVIDER=std
		-DOGRE_FULL_RPATH=no
		-DOGRE_INSTALL_DOCS=yes
		-DOGRE_INSTALL_SAMPLES=yes
		-DOGRE_INSTALL_SAMPLES_SOURCE=yes
		-DOGRE_LEGACY_ANIMATIONS=no
		-DOGRE_PROFILING_PROVIDER=none
		-DOGRE_USE_BOOST=no
		-DOGRE_CONFIG_DOUBLE=no
````
I was able to compile with these settings after applying the following three patches.

## OgrePVRTCCodec.cpp
The first error was in `OgrePVRTCCodec.cpp`, which was just a missing include, so I keep this short.

### Error:
````
/tmp/ogre-next-2.1/OgreMain/src/OgrePVRTCCodec.cpp: In member function ‘virtual Ogre::Codec::DecodeResult Ogre::PVRTCCodec::decode(Ogre::DataStreamPtr&) const’:
/tmp/ogre-next-2.1/OgreMain/src/OgrePVRTCCodec.cpp:164:15: error: invalid use of incomplete type ‘class Ogre::DataStream’
  164 |         stream->read(&headerV2, sizeof(PVRTCTexHeaderV2));
      |               ^~
````

### Patch:
````
--- a/OgreMain/src/OgrePVRTCCodec.cpp	2020-04-27 20:00:44.816974345 +0200
+++ b/OgreMain/src/OgrePVRTCCodec.cpp	2020-04-27 20:03:49.186962841 +0200
@@ -33,6 +33,7 @@
 #include "OgreException.h"
 #include "OgreLogManager.h"
 #include "OgreBitwise.h"
+#include "OgreDataStream.h"
 
 #define FOURCC(c0, c1, c2, c3) (c0 | (c1 << 8) | (c2 << 16) | (c3 << 24))
 #define PVR_TEXTURE_FLAG_TYPE_MASK  0xff
````

## OgreGrid2DPageStrategy.cpp, OgreGrid3DPageStrategy.cpp
Both suffer the same problem, so I only post the error once and then the two patches.

Error:
````
FAILED: Components/Paging/CMakeFiles/OgrePaging.dir/src/OgreGrid3DPageStrategy.cpp.o 
/usr/lib/ccache/bin/x86_64-pc-linux-gnu-g++
  -DBOOST_THREAD_VERSION=4 -DOGRE_PAGING_EXPORTS -DOgrePaging_EXPORTS
  -D_MT -D_USRDLL -I/tmp/ogre-next-2.1/OgreMain/include -Iinclude -I/usr/include/freetype2
  -I/usr/include/OIS -I/opt/nvidia-cg-toolkit/include/Cg -I/opt/nvidia-cg-toolkit/include
  -I/tmp/ogre-next-2.1 -I/tmp/ogre-next-2.1/Components/Paging/include  -Wall -Winit-self
  -Wno-overloaded-virtual -Wcast-qual -Wwrite-strings -Wextra -Wno-unused-parameter
  -Wshadow -Wno-missing-field-initializers -Wno-long-long -Wno-unused-but-set-parameter
  -march=native -O2 -pipe -ggdb -DOGRE_DEBUG_MODE=0 -Wno-deprecated-copy
  -Wno-class-memaccess -msse -msse2 -fPIC   -fPIC -pthread
  -DOGRE_GCC_VISIBILITY -fvisibility=hidden -fvisibility-inlines-hidden -MD
  -MT Components/Paging/CMakeFiles/OgrePaging.dir/src/OgreGrid3DPageStrategy.cpp.o
  -MF Components/Paging/CMakeFiles/OgrePaging.dir/src/OgreGrid3DPageStrategy.cpp.o.d
  -o Components/Paging/CMakeFiles/OgrePaging.dir/src/OgreGrid3DPageStrategy.cpp.o
  -c /tmp/ogre-next-2.1/Components/Paging/src/OgreGrid3DPageStrategy.cpp
/tmp/ogre-next-2.1/Components/Paging/src/OgreGrid3DPageStrategy.cpp:
    In member function ‘virtual void Ogre::Grid3DPageStrategy::updateDebugDisplay(Ogre::Page*, Ogre::SceneNode*)’:
/tmp/ogre-next-2.1/Components/Paging/src/OgreGrid3DPageStrategy.cpp:370:23:
    error: ‘class Ogre::Pass’ has no member named ‘setLightingEnabled’; did you mean ‘setLightScissoringEnabled’?
  370 |                 pass->setLightingEnabled(false);
      |                       ^~~~~~~~~~~~~~~~~~
      |                       setLightScissoringEnabled
/tmp/ogre-next-2.1/Components/Paging/src/OgreGrid3DPageStrategy.cpp:372:23:
    error: ‘class Ogre::Pass’ has no member named ‘setDepthWriteEnabled’; did you mean ‘setPointSpritesEnabled’?
  372 |                 pass->setDepthWriteEnabled(false);
      |                       ^~~~~~~~~~~~~~~~~~~~
      |                       setPointSpritesEnabled
/tmp/ogre-next-2.1/Components/Paging/src/OgreGrid3DPageStrategy.cpp:386:36:
    error: ‘RenderOperation’ has not been declared
  386 |                 mo->begin(matName, RenderOperation::OT_LINE_STRIP);
      |                                    ^~~~~~~~~~~~~~~
````

### Patches:
````
--- a/Components/Paging/src/OgreGrid2DPageStrategy.cpp	2020-04-28 09:43:23.119894582 +0200
+++ b/Components/Paging/src/OgreGrid2DPageStrategy.cpp	2020-04-28 09:44:00.844892228 +0200
@@ -405,9 +405,9 @@
             {
                 mat = MaterialManager::getSingleton().create(matName, ResourceGroupManager::DEFAULT_RESOURCE_GROUP_NAME);
                 Pass* pass = mat->getTechnique(0)->getPass(0);
-                pass->setLightingEnabled(false);
+                //pass->setLightingEnabled(false);
                 pass->setVertexColourTracking(TVC_AMBIENT);
-                pass->setDepthWriteEnabled(false);
+                //pass->setDepthWriteEnabled(false);
                 mat->load();
             }
 
@@ -416,7 +416,7 @@
             if (sn->numAttachedObjects() == 0)
             {
                 mo = p->getParentSection()->getSceneManager()->createManualObject();
-                mo->begin(matName, RenderOperation::OT_LINE_STRIP);
+                mo->begin(matName, OperationType::OT_LINE_STRIP);
             }
             else
             {
````
and
````
--- a/Components/Paging/src/OgreGrid3DPageStrategy.cpp	2020-04-28 09:31:06.301940556 +0200
+++ b/Components/Paging/src/OgreGrid3DPageStrategy.cpp	2020-04-28 09:40:51.777904025 +0200
@@ -367,9 +367,9 @@
             {
                 mat = MaterialManager::getSingleton().create(matName, ResourceGroupManager::DEFAULT_RESOURCE_GROUP_NAME);
                 Pass* pass = mat->getTechnique(0)->getPass(0);
-                pass->setLightingEnabled(false);
+                //pass->setLightingEnabled(false);
                 pass->setVertexColourTracking(TVC_AMBIENT);
-                pass->setDepthWriteEnabled(false);
+                //pass->setDepthWriteEnabled(false);
                 mat->load();
             }
 
@@ -383,7 +383,7 @@
             else
             {
                 mo = p->getParentSection()->getSceneManager()->createManualObject();
-                mo->begin(matName, RenderOperation::OT_LINE_STRIP);
+                mo->begin(matName, OperationType::OT_LINE_STRIP);
             }
 
             ColourValue vcol = ColourValue::Green;
````

## No Pull Request
I have decided to post an issue rather then creating a pull request, because I know too little about the inner workings of Ogre-2.1 to be sure these patches are sane. Everything compiles fine, now, which is great. But do these changes also end up in a working product?

However, keep up the great work! Ogre was, is, and always will be just awesome!

**Comment by darksylinc** [comment]
Hi!

Thanks for trying Ogre 2.1!

The following settings you turned on are not supported in 2.1 (haven't been ported):

* OGRE_BUILD_COMPONENT_PAGING
* OGRE_BUILD_RENDERSYSTEM_GLES2


The following setting negatively affects performance and should be enabled if an application makes explicit use of it:
* OGRE_CONFIG_ENABLE_FINE_LIGHT_MASK_GRANULARITY

The use of OGRE_CONFIG_THREADS is recommended to be set to 0.

The patch for OgrePVRTCCodec.cpp is welcomed!
The patch for OgreGrid3DPageStrategy & co. may fix the compiler errors but the component still won't work.

Cheers!
Matias

**Comment by Yamakuzure** [comment]
Thanks alot for your answer!

I will adept the options accordingly.

There are also two severe warnings that hint that runtime failures *might* occur:

## warning 1
````
OgreMain/include/OgreMatrix4.h:624:65: warning:
  ‘parentNodeTransform.Ogre::Matrix4::<anonymous>.Ogre::Matrix4::<unnamed union>::m[3][0]’
  is used uninitialized in this function [-Wuninitialized]
````

## Fix 1
````
--- a/OgreMain/include/OgreMatrix4.h  2020-04-28 10:55:57.221622903 +0200
+++ b/OgreMain/include/OgreMatrix4.h      2020-04-28 11:04:23.420591318 +0200
@@ -95,7 +95,7 @@
             @note
                 It does <b>NOT</b> initialize the matrix for efficiency.
         */
-        inline Matrix4()
+        inline Matrix4(): m{ 0 }
         {
         }
 
````

## Warning 2:
````
Samples/2.0/Tutorials/Tutorial_Terrain/src/Terra/TerrainCell.cpp:136:22: warning:
  dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
````

## Fix 2:
````
--- a/Samples/2.0/Tutorials/Tutorial_Terrain/src/Terra/TerrainCell.cpp        2020-04-28 18:10:40.416995414 +0200
+++ b/Samples/2.0/Tutorials/Tutorial_Terrain/src/Terra/TerrainCell.cpp    2020-04-28 18:30:46.074920186 +0200
@@ -133,7 +133,11 @@
         gpuPtr[0] = m_verticesPerLine;
         gpuPtr[1] = m_lodLevel;
         gpuPtr[2] = vao->getPrimitiveCount() / m_verticesPerLine - 2u;
-        gpuPtr[3] = *reinterpret_cast<uint32*>( &m_parentTerra->m_skirtSize );
+       /* Triggers: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
+         * gpuPtr[3] = *reinterpret_cast<uint32*>( &m_parentTerra->m_skirtSize );
+        * See: http://zaynar.co.uk/docs/float-aliasing.html
+        */
+       memcpy(&gpuPtr[3], &m_parentTerra->m_skirtSize, sizeof(gpuPtr[3]));
 
         //ivec4 xzTexPosBounds
         ((int32*RESTRICT_ALIAS)gpuPtr)[4] = m_gridX;
````

(`Sample_Tutorial_Terrain-2.1.0` works wonderfully, btw, even on my intel chip. :wink: )

**Comment by darksylinc** [comment]
Hi!

https://github.com/OGRECave/ogre-next/commit/d1c1116924ca537c1f061ed5422dd9a5207d989a

> There are also two severe warnings that hint that runtime failures _might_ occur:
> ## warning 1
> 
> ```
> OgreMain/include/OgreMatrix4.h:624:65: warning:
>   ‘parentNodeTransform.Ogre::Matrix4::<anonymous>.Ogre::Matrix4::<unnamed union>::m[3][0]’
>   is used uninitialized in this function [-Wuninitialized]

That bug was fixed in master.
I just [cherry picked the commit](https://github.com/OGRECave/ogre-next/commit/d1c1116924ca537c1f061ed5422dd9a5207d989a) to 2.1
Thanks

btw as the comment above the Matrix4 constructor said, 'It does <b>NOT</b> initialize the matrix for efficiency' :laughing:  

> ## Warning 2:
> 
> ```
> Samples/2.0/Tutorials/Tutorial_Terrain/src/Terra/TerrainCell.cpp:136:22: warning:
>   dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
> ```
> 
> ## Fix 2:
> 
> ```
> --- a/Samples/2.0/Tutorials/Tutorial_Terrain/src/Terra/TerrainCell.cpp        2020-04-28 18:10:40.416995414 +0200
> +++ b/Samples/2.0/Tutorials/Tutorial_Terrain/src/Terra/TerrainCell.cpp    2020-04-28 18:30:46.074920186 +0200
> @@ -133,7 +133,11 @@
>          gpuPtr[0] = m_verticesPerLine;
>          gpuPtr[1] = m_lodLevel;
>          gpuPtr[2] = vao->getPrimitiveCount() / m_verticesPerLine - 2u;
> -        gpuPtr[3] = *reinterpret_cast<uint32*>( &m_parentTerra->m_skirtSize );
> +       /* Triggers: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
> +         * gpuPtr[3] = *reinterpret_cast<uint32*>( &m_parentTerra->m_skirtSize );
> +        * See: http://zaynar.co.uk/docs/float-aliasing.html
> +        */
> +       memcpy(&gpuPtr[3], &m_parentTerra->m_skirtSize, sizeof(gpuPtr[3]));
>  
>          //ivec4 xzTexPosBounds
>          ((int32*RESTRICT_ALIAS)gpuPtr)[4] = m_gridX;
> ```

Mmmm... sadly we're aware of it and restrict aliasing is in several places in our code.

It affects many projects who need to deal with hardware, and the same reason the Linux kernel disables strict aliasing. The workarounds for strict aliasing are insane in both readability and code generation, and std::bit_cast came way too late.

Perhaps using a macro to reinterpret values e.g.
`gpuPtr[3] = OGRE_BITCAST( uint32, m_parentTerra->m_skirtSize );` would allow us to replace the bitcast with the solution of your choice (anonymous inline union, bit_cast, memcpy, dangerous reinterpret_cast) while not hurting readability.

I just opened #91 for this, since it warrants its own ticket.

> (`Sample_Tutorial_Terrain-2.1.0` works wonderfully, btw, even on my intel chip. wink )

Thanks! It's a shame the default look looks so 'debuggy'. With enough tweaks [Terra can look very sweet](https://apps.apple.com/us/app/alliance-air-war/id1059604202).

**Comment by Yamakuzure** [comment]
I took a look into d1c1116 and am currently testing to use that instead of the initialization patch.
Last night it came to my mind, that instead of enforcing an initialization, the "used uninitialized" warning should instead taken as a hint, that the class/method is used wrongly. Your cherry-picked commit looks like it would fix that, which is indeed preferably.

The build just finished and the warning is gone. Great!

As for the type-punning, the "`memcpy`" method has the advantage, that it is the most performant. (And most portable)

> Even if the float is not a compile-time constant, the compiler just generates code to store the value into memory (`fstps`) then loads it back into an integer register (`movl`).

Thanks again for your help!

**Comment by Yamakuzure** [comment]
Everything is solid now, and I am looking forward to taking a look at 2.2, so I guess it is safe to close this?
