### ISSUE TITLE
Ogre 2.2.1 fails to build - missing #include in OgrePVRTCCodec.cpp?

### ISSUE THREAD

**Issue by rainerdeyke** [OGRECave/ogre-next#98]
#### System Information
- Ogre Version: 2.2.1; also git master ca99750ac454570a8b7a655e2081721f3554d96c
- Operating System / Platform: Ubuntu 16.04 LTS
- RenderSystem: OpenGL?
- GPU: doesn't matter

#### Detailled description
I get the following error when trying to build Ogre 2.2.1:
```
/home/rainer/projects/starfire/intermediate/libs/stable/ogre-next-2.2.1/OgreMain/src/OgrePVRTCCodec.cpp:164:15: error: member access into incomplete type 'Ogre::DataStream'
        stream->read(&headerV2, sizeof(PVRTCTexHeaderV2));
```
It appears that OgrePVRTCCodec.cpp should be #including OgreDataStream.h, but doesn't.

Complete build log [here](https://drive.google.com/open?id=1Po53WUn4ObN5P6KM3mZGto1raX2PhH_k).  Apparently too long to attach directly to the issue.

**Comment by darksylinc** [comment]
Fixed in v2.2.2
